// ---------------------------------------------------------
// Copyright (c) North East London ICB. All rights reserved.
// ---------------------------------------------------------

using LondonFhirService.Providers.FHIR.STU3.Abstractions.Models.Capabilities;
using LondonFhirService.Providers.FHIR.STU3.Abstractions.Models.Resources;

namespace LondonFhirService.Providers.FHIR.STU3.Abstractions
{
    /// <summary>STU3 provider contract.</summary>
    public interface IFhirProvider
    {
        string ProviderName { get; }
        string Source { get; }
        string Code { get; }
        string System { get; }
        ProviderCapabilities Capabilities { get; }
        /// <summary>Access FHIR Account resources.</summary>
        IAccountResource Accounts { get; }
        /// <summary>Access FHIR ActivityDefinition resources.</summary>
        IActivityDefinitionResource ActivityDefinitions { get; }
        /// <summary>Access FHIR AdverseEvent resources.</summary>
        IAdverseEventResource AdverseEvents { get; }
        /// <summary>Access FHIR AllergyIntolerance resources.</summary>
        IAllergyIntoleranceResource AllergyIntolerances { get; }
        /// <summary>Access FHIR Appointment resources.</summary>
        IAppointmentResource Appointments { get; }
        /// <summary>Access FHIR AppointmentResponse resources.</summary>
        IAppointmentResponseResource AppointmentResponses { get; }
        /// <summary>Access FHIR AuditEvent resources.</summary>
        IAuditEventResource AuditEvents { get; }
        /// <summary>Access FHIR Basic resources.</summary>
        IBasicResource Basics { get; }
        /// <summary>Access FHIR Binary resources.</summary>
        IBinaryResource Binaries { get; }
        /// <summary>Access FHIR BodySite resources.</summary>
        IBodySiteResource BodySites { get; }
        /// <summary>Access FHIR Bundle resources.</summary>
        IBundleResource Bundles { get; }
        /// <summary>Access FHIR CapabilityStatement resources.</summary>
        ICapabilityStatementResource CapabilityStatements { get; }
        /// <summary>Access FHIR CarePlan resources.</summary>
        ICarePlanResource CarePlans { get; }
        /// <summary>Access FHIR CareTeam resources.</summary>
        ICareTeamResource CareTeams { get; }
        /// <summary>Access FHIR ChargeItem resources.</summary>
        IChargeItemResource ChargeItems { get; }
        /// <summary>Access FHIR Claim resources.</summary>
        IClaimResource Claims { get; }
        /// <summary>Access FHIR ClaimResponse resources.</summary>
        IClaimResponseResource ClaimResponses { get; }
        /// <summary>Access FHIR ClinicalImpression resources.</summary>
        IClinicalImpressionResource ClinicalImpressions { get; }
        /// <summary>Access FHIR CodeSystem resources.</summary>
        ICodeSystemResource CodeSystems { get; }
        /// <summary>Access FHIR Communication resources.</summary>
        ICommunicationResource Communications { get; }
        /// <summary>Access FHIR CommunicationRequest resources.</summary>
        ICommunicationRequestResource CommunicationRequests { get; }
        /// <summary>Access FHIR CompartmentDefinition resources.</summary>
        ICompartmentDefinitionResource CompartmentDefinitions { get; }
        /// <summary>Access FHIR Composition resources.</summary>
        ICompositionResource Compositions { get; }
        /// <summary>Access FHIR ConceptMap resources.</summary>
        IConceptMapResource ConceptMaps { get; }
        /// <summary>Access FHIR Condition resources.</summary>
        IConditionResource Conditions { get; }
        /// <summary>Access FHIR Consent resources.</summary>
        IConsentResource Consents { get; }
        /// <summary>Access FHIR Contract resources.</summary>
        IContractResource Contracts { get; }
        /// <summary>Access FHIR Coverage resources.</summary>
        ICoverageResource Coverages { get; }
        /// <summary>Access FHIR DataElement resources.</summary>
        IDataElementResource DataElements { get; }
        /// <summary>Access FHIR DetectedIssue resources.</summary>
        IDetectedIssueResource DetectedIssues { get; }
        /// <summary>Access FHIR Device resources.</summary>
        IDeviceResource Devices { get; }
        /// <summary>Access FHIR DeviceComponent resources.</summary>
        IDeviceComponentResource DeviceComponents { get; }
        /// <summary>Access FHIR DeviceMetric resources.</summary>
        IDeviceMetricResource DeviceMetrics { get; }
        /// <summary>Access FHIR DeviceRequest resources.</summary>
        IDeviceRequestResource DeviceRequests { get; }
        /// <summary>Access FHIR DeviceUseStatement resources.</summary>
        IDeviceUseStatementResource DeviceUseStatements { get; }
        /// <summary>Access FHIR DiagnosticReport resources.</summary>
        IDiagnosticReportResource DiagnosticReports { get; }
        /// <summary>Access FHIR DocumentManifest resources.</summary>
        IDocumentManifestResource DocumentManifests { get; }
        /// <summary>Access FHIR DocumentReference resources.</summary>
        IDocumentReferenceResource DocumentReferences { get; }
        /// <summary>Access FHIR EligibilityRequest resources.</summary>
        IEligibilityRequestResource EligibilityRequests { get; }
        /// <summary>Access FHIR EligibilityResponse resources.</summary>
        IEligibilityResponseResource EligibilityResponses { get; }
        /// <summary>Access FHIR Encounter resources.</summary>
        IEncounterResource Encounters { get; }
        /// <summary>Access FHIR Endpoint resources.</summary>
        IEndpointResource Endpoints { get; }
        /// <summary>Access FHIR EnrollmentRequest resources.</summary>
        IEnrollmentRequestResource EnrollmentRequests { get; }
        /// <summary>Access FHIR EnrollmentResponse resources.</summary>
        IEnrollmentResponseResource EnrollmentResponses { get; }
        /// <summary>Access FHIR EpisodeOfCare resources.</summary>
        IEpisodeOfCareResource EpisodeOfCares { get; }
        /// <summary>Access FHIR ExpansionProfile resources.</summary>
        IExpansionProfileResource ExpansionProfiles { get; }
        /// <summary>Access FHIR ExplanationOfBenefit resources.</summary>
        IExplanationOfBenefitResource ExplanationOfBenefits { get; }
        /// <summary>Access FHIR FamilyMemberHistory resources.</summary>
        IFamilyMemberHistoryResource FamilyMemberHistories { get; }
        /// <summary>Access FHIR Flag resources.</summary>
        IFlagResource Flags { get; }
        /// <summary>Access FHIR Goal resources.</summary>
        IGoalResource Goals { get; }
        /// <summary>Access FHIR GraphDefinition resources.</summary>
        IGraphDefinitionResource GraphDefinitions { get; }
        /// <summary>Access FHIR Group resources.</summary>
        IGroupResource Groups { get; }
        /// <summary>Access FHIR GuidanceResponse resources.</summary>
        IGuidanceResponseResource GuidanceResponses { get; }
        /// <summary>Access FHIR HealthcareService resources.</summary>
        IHealthcareServiceResource HealthcareServices { get; }
        /// <summary>Access FHIR ImagingManifest resources.</summary>
        IImagingManifestResource ImagingManifests { get; }
        /// <summary>Access FHIR ImagingStudy resources.</summary>
        IImagingStudyResource ImagingStudies { get; }
        /// <summary>Access FHIR Immunization resources.</summary>
        IImmunizationResource Immunizations { get; }
        /// <summary>Access FHIR ImmunizationRecommendation resources.</summary>
        IImmunizationRecommendationResource ImmunizationRecommendations { get; }
        /// <summary>Access FHIR ImplementationGuide resources.</summary>
        IImplementationGuideResource ImplementationGuides { get; }
        /// <summary>Access FHIR Library resources.</summary>
        ILibraryResource Libraries { get; }
        /// <summary>Access FHIR Linkage resources.</summary>
        ILinkageResource Linkages { get; }
        /// <summary>Access FHIR List resources.</summary>
        IListResource Lists { get; }
        /// <summary>Access FHIR Location resources.</summary>
        ILocationResource Locations { get; }
        /// <summary>Access FHIR Measure resources.</summary>
        IMeasureResource Measures { get; }
        /// <summary>Access FHIR MeasureReport resources.</summary>
        IMeasureReportResource MeasureReports { get; }
        /// <summary>Access FHIR Media resources.</summary>
        IMediaResource Media { get; }
        /// <summary>Access FHIR Medication resources.</summary>
        IMedicationResource Medications { get; }
        /// <summary>Access FHIR MedicationAdministration resources.</summary>
        IMedicationAdministrationResource MedicationAdministrations { get; }
        /// <summary>Access FHIR MedicationDispense resources.</summary>
        IMedicationDispenseResource MedicationDispenses { get; }
        /// <summary>Access FHIR MedicationRequest resources.</summary>
        IMedicationRequestResource MedicationRequests { get; }
        /// <summary>Access FHIR MedicationStatement resources.</summary>
        IMedicationStatementResource MedicationStatements { get; }
        /// <summary>Access FHIR MessageDefinition resources.</summary>
        IMessageDefinitionResource MessageDefinitions { get; }
        /// <summary>Access FHIR MessageHeader resources.</summary>
        IMessageHeaderResource MessageHeaders { get; }
        /// <summary>Access FHIR NamingSystem resources.</summary>
        INamingSystemResource NamingSystems { get; }
        /// <summary>Access FHIR NutritionOrder resources.</summary>
        INutritionOrderResource NutritionOrders { get; }
        /// <summary>Access FHIR Observation resources.</summary>
        IObservationResource Observations { get; }
        /// <summary>Access FHIR OperationDefinition resources.</summary>
        IOperationDefinitionResource OperationDefinitions { get; }
        /// <summary>Access FHIR OperationOutcome resources.</summary>
        IOperationOutcomeResource OperationOutcomes { get; }
        /// <summary>Access FHIR Organization resources.</summary>
        IOrganizationResource Organizations { get; }
        /// <summary>Access FHIR Parameters resources.</summary>
        IParametersResource Parameters { get; }
        /// <summary>Access FHIR Patient resources.</summary>
        IPatientResource Patients { get; }
        /// <summary>Access FHIR PaymentNotice resources.</summary>
        IPaymentNoticeResource PaymentNotices { get; }
        /// <summary>Access FHIR PaymentReconciliation resources.</summary>
        IPaymentReconciliationResource PaymentReconciliations { get; }
        /// <summary>Access FHIR Person resources.</summary>
        IPersonResource Persons { get; }
        /// <summary>Access FHIR PlanDefinition resources.</summary>
        IPlanDefinitionResource PlanDefinitions { get; }
        /// <summary>Access FHIR Practitioner resources.</summary>
        IPractitionerResource Practitioners { get; }
        /// <summary>Access FHIR PractitionerRole resources.</summary>
        IPractitionerRoleResource PractitionerRoles { get; }
        /// <summary>Access FHIR Procedure resources.</summary>
        IProcedureResource Procedures { get; }
        /// <summary>Access FHIR ProcedureRequest resources.</summary>
        IProcedureRequestResource ProcedureRequests { get; }
        /// <summary>Access FHIR ProcessRequest resources.</summary>
        IProcessRequestResource ProcessRequests { get; }
        /// <summary>Access FHIR ProcessResponse resources.</summary>
        IProcessResponseResource ProcessResponses { get; }
        /// <summary>Access FHIR Provenance resources.</summary>
        IProvenanceResource Provenances { get; }
        /// <summary>Access FHIR Questionnaire resources.</summary>
        IQuestionnaireResource Questionnaires { get; }
        /// <summary>Access FHIR QuestionnaireResponse resources.</summary>
        IQuestionnaireResponseResource QuestionnaireResponses { get; }
        /// <summary>Access FHIR ReferralRequest resources.</summary>
        IReferralRequestResource ReferralRequests { get; }
        /// <summary>Access FHIR RelatedPerson resources.</summary>
        IRelatedPersonResource RelatedPersons { get; }
        /// <summary>Access FHIR RequestGroup resources.</summary>
        IRequestGroupResource RequestGroups { get; }
        /// <summary>Access FHIR ResearchStudy resources.</summary>
        IResearchStudyResource ResearchStudies { get; }
        /// <summary>Access FHIR ResearchSubject resources.</summary>
        IResearchSubjectResource ResearchSubjects { get; }
        /// <summary>Access FHIR RiskAssessment resources.</summary>
        IRiskAssessmentResource RiskAssessments { get; }
        /// <summary>Access FHIR Schedule resources.</summary>
        IScheduleResource Schedules { get; }
        /// <summary>Access FHIR SearchParameter resources.</summary>
        ISearchParameterResource SearchParameters { get; }
        /// <summary>Access FHIR Sequence resources.</summary>
        ISequenceResource Sequences { get; }
        /// <summary>Access FHIR ServiceDefinition resources.</summary>
        IServiceDefinitionResource ServiceDefinitions { get; }
        /// <summary>Access FHIR Slot resources.</summary>
        ISlotResource Slots { get; }
        /// <summary>Access FHIR Specimen resources.</summary>
        ISpecimenResource Specimens { get; }
        /// <summary>Access FHIR StructureDefinition resources.</summary>
        IStructureDefinitionResource StructureDefinitions { get; }
        /// <summary>Access FHIR StructureMap resources.</summary>
        IStructureMapResource StructureMaps { get; }
        /// <summary>Access FHIR Subscription resources.</summary>
        ISubscriptionResource Subscriptions { get; }
        /// <summary>Access FHIR Substance resources.</summary>
        ISubstanceResource Substances { get; }
        /// <summary>Access FHIR SupplyDelivery resources.</summary>
        ISupplyDeliveryResource SupplyDeliveries { get; }
        /// <summary>Access FHIR SupplyRequest resources.</summary>
        ISupplyRequestResource SupplyRequests { get; }
        /// <summary>Access FHIR Task resources.</summary>
        ITaskResource Tasks { get; }
        /// <summary>Access FHIR TestScript resources.</summary>
        ITestScriptResource TestScripts { get; }
        /// <summary>Access FHIR TestReport resources.</summary>
        ITestReportResource TestReports { get; }
        /// <summary>Access FHIR ValueSet resources.</summary>
        IValueSetResource ValueSets { get; }
        /// <summary>Access FHIR VisionPrescription resources.</summary>
        IVisionPrescriptionResource VisionPrescriptions { get; }
    }
}
